name: "Github Cron"
run-name: ${{ github.actor }} is learning GitHub Cron

on:
  schedule:
    - cron: '5 * * * *'

jobs:
  test-github-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Every Time
        run: echo "This will run every minute"
